### ISSUE TITLE
brew install instructions throwing error

### ISSUE THREAD

**Issue by tqb-zynga** [SPMDestinations/homebrew-tap#15]
I'm running macOS 12.1 on an M1. I have brew installed at /opt/homebrew.

I ran `arch -x86_64 brew tap SPMDestinations/tap` and everything worked fine. When I ran `arch -x86_64 brew install spm-dest-5.3-x86_64-ubuntu16.04` though, I got:

> Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!
> To rerun under ARM use:
>     arch -arm64 brew install ...
> To install under x86_64, install Homebrew into /usr/local.

**Comment by helje5** [comment]
/opt/homebrew is the M1 native version, /usr/local the one for x86. I think you just need to remove the arch
