### ISSUE TITLE
Linking libz fails (e.g. used in async-http-client)

### ISSUE THREAD

**Issue by MoridinBG** [SPMDestinations/homebrew-tap#9]
I have a well working setup that uses `spm-dest-5.2-x86_64-amazonlinux2` to cross-compile Swift lambdas for AWS.
When I try to compile any package that adds https://github.com/swift-server/async-http-client as a dependency, linking fails:

```
ld.lld: error: can't create dynamic relocation R_X86_64_32S against symbol: _length_code in readonly segment; recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
>>> defined in /usr/local/lib/swift/dst/x86_64-unknown-linux/swift-5.2-amazonlinux2.xtoolchain/x86_64-amazonlinux2.sdk/usr/lib/gcc/x86_64-redhat-linux/7/../../../../lib64/libz.a(trees.o)
>>> referenced by deflate.o:(deflate_slow) in archive /usr/local/lib/swift/dst/x86_64-unknown-linux/swift-5.2-amazonlinux2.xtoolchain/x86_64-amazonlinux2.sdk/usr/lib/gcc/x86_64-redhat-linux/7/../../../../lib64/libz.a
```

This repeats 19 times and at the end
```
ld.lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
```

If I remove the dependency on AsyncHTTPClient it compiles successfully. I have tried the 5.3 and ubuntu destinations too with no success.
I have also tried completely empty packages with `swift package init --type executable` where I have only added the dependency to the Package.swift with the same result.

When building the same package natively in an amazonlinux2 Docker image, it builds successfully even with AsyncHTTPClient included.

**Comment by helje5** [comment]
Interesting, the issue is linking libz which is probably used in the client for decompression. Maybe the Docker version links it dynamically.

**Comment by helje5** [comment]
Steps to repro:
```
mkdir macro-test && cd macro-test && swift package init --type=executable
```

Add those deps to the Package.swift:
```
        .package(url: "https://github.com/swift-server/async-http-client.git", from: "1.0.0")
            dependencies: [ .product(name: "AsyncHTTPClient", package: "async-http-client") ]),
```

```
swift build --destination /usr/local/lib/swift/dst/x86_64-unknown-linux/swift-5.2-amazonlinux2.xtoolchain/destination.json
```

**Comment by helje5** [comment]
And the failing linker call looks like this:
```
/usr/local/lib/swift/dst/x86_64-unknown-linux/swift-5.2-amazonlinux2.xtoolchain/swift.xctoolchain/usr/bin/swiftc \
  -use-ld=lld \
  -tools-directory /usr/local/lib/swift/dst/x86_64-unknown-linux/swift-5.2-amazonlinux2.xtoolchain/swift.xctoolchain/usr/bin \
  -sdk /usr/local/lib/swift/dst/x86_64-unknown-linux/swift-5.2-amazonlinux2.xtoolchain/x86_64-amazonlinux2.sdk \
  -lstdc++ \
  -L /private/tmp/macro-test/.build/x86_64-unknown-linux/debug \
  -o /private/tmp/macro-test/.build/x86_64-unknown-linux/debug/macro-test \
  -module-name macro_test \
  -emit-executable \
  -Xlinker '-rpath=$ORIGIN' @/private/tmp/macro-test/.build/x86_64-unknown-linux/debug/macro-test.product/Objects.LinkFileList -target x86_64-unknown-linux \
  -lz \
  -L /usr/local/Cellar/spm-dest-5.2-x86_64-amazonlinux2/5.2.5_2/lib/swift/dst/x86_64-unknown-linux/swift-5.2-amazonlinux2.xtoolchain/swift.xctoolchain/usr/lib
```

**Comment by helje5** [comment]
The best fix would be to get static linking working: https://github.com/SwiftXcode/swift-lambda/issues/3

**Comment by helje5** [comment]
So when building w/ Docker, libz is linked dynamically:
```
ldd .build/x86_64-unknown-linux-gnu/debug/macro-test
	linux-vdso.so.1 (0x00007ffe9e395000)
...
	libz.so.1 => /lib64/libz.so.1 (0x00007ff407275000)
```
So it is probably sufficient to add the libz dylib to the SDK.

**Comment by helje5** [comment]
OK, that did it. Added a few so libs.

**Comment by MoridinBG** [comment]
That got resolved fast!
I learned so much about linking today. The error message sent me in all kinds of wrong directions, but now I have a better idea of how things work.
I managed to get it working after your comment about adding it to the sdk. Static linking would be amazing!
